console.log("hahahah");
console.log("nananana");
console.log("hahahah");
console.log("hhhhhh");
console.log("hahahah");
console.log("hahahah");
console.log("hahahah");
console.log("hahahah");
console.log("last");
